name: Deploy

on:
 push:
  branches: 
   - main

jobs:
 build:
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@v1

    - name: Copy repository contents via scp
      uses: appleboy/scp-action@master
      env:
        HOST: ${{ secrets.HOST }}
        USERNAME: ${{ secrets.USERNAME }}
        PORT: ${{ secrets.PORT }}
        KEY: ${{ secrets.SSHKEY }}
      with:
        source: "."
        target: "/srv/youchoose/YouChoose"

    - name: Pip install and python main.py
      uses: appleboy/ssh-action@master
      env:
       AUTHORIZATION_IGDB: ${{ secrets.AUTHORIZATION_IGDB }}
       DISCORD_TOKEN: ${{ secrets.DISCORD_TOKEN }}
       TWITCH_CLIENT_ID: ${{ secrets.TWITCH_CLIENT_ID }}
       SHA: ${{ github.sha }}
      with:
        host: ${{ secrets.HOST }}
        USERNAME: ${{ secrets.USERNAME }}
        PORT: ${{ secrets.PORT }}
        KEY: ${{ secrets.SSHKEY }}
        envs: AUTHORIZATION_IGDB,DISCORD_TOKEN,TWITCH_CLIENT_ID
        script: |
         export AUTHORIZATION_IGDB=$AUTHORIZATION_IGDB
         export DISCORD_TOKEN=$DISCORD_TOKEN
         export TWITCH_CLIENT_ID=$TWITCH_CLIENT_ID
         /srv/youchoose/venv-youchoose/bin/python3.8 -m pip install --upgrade pip
         /srv/youchoose/venv-youchoose/bin/python3.8 -m pip install -r /srv/youchoose/YouChoose/requirements.txt
         systemctl restart supervisord
