name: Deploy

on: [push]

jobs:
 build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1

    - name: Copy repository contents via scp
      uses: appleboy/scp-action@master
      env:
        HOST: ${{ secrets.HOST }}
        USERNAME: ${{ secrets.USERNAME }}
        PORT: ${{ secrets.PORT }}
        KEY: ${{ secrets.SSHKEY }}
      with:
        source: "."
        target: "/srv/youchoose/YouChoose"

    - name: Executing remote command
      uses: appleboy/ssh-action@master
      env:
       AUTHORIZATION_IGDB: ${{ secrets.AUTHORIZATION_IGDB }}
       DISCORD_TOKEN: ${{ secrets.DISCORD_TOKEN }}
       TWITCH_CLIENT_ID: ${{ secrets.TWITCH_CLIENT_ID }}
      with:
        host: ${{ secrets.HOST }}
        USERNAME: ${{ secrets.USERNAME }}
        PORT: ${{ secrets.PORT }}
        KEY: ${{ secrets.SSHKEY }}
        envs: AUTHORIZATION_IGDB,DISCORD_TOKEN,TWITCH_CLIENT_ID
        script: |
         $AUTHORIZATION_IGDB
         /srv/youchoose/venv-youchoose/bin/python3.8 -m pip install -r /srv/youchoose/YouChoose/requirements.txt
         /srv/youchoose/venv-youchoose/bin/python3.8 /srv/youchoose/YouChoose/main.py
