name: Linting

on: [pull_request]

jobs:
  styles:
    runs-on: self-hosted
    name: Linting
    steps:
      - uses: actions/checkout@master
      - name: Run Action Step
        id: run-linting
        uses: LakshitF/pylint3-action@master
      - uses: github-actions-up-and-running/pr-comment@v1.0.0
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          message: ${{ steps.run-linting.outputs.* }}
