name: Linting

on: [pull_request]

jobs:
  styles:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v1
      - uses: github-actions-up-and-running/pr-comment@v1.0.0
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          message: "Hello github actions"
