name: Linting

on: [pull_request]

jobs:
  styles:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v1
      - name: GitHub Action for pylint
        uses: cclauss/GitHub-Action-for-pylint@master
        with:
          args: pylint --help
        id: run-linting
      - name: Comment PR
        uses: thollander/actions-comment-pull-request@master
        with:
          message: 'Example of message !'
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
