name: Linter

on: pull_request

jobs:
  linter:
    name: linter
    runs-on: ubuntu-latest
    
    steps:
      - name: Run flake8 on your PR - with annotations!
        uses: tayfun/flake8-your-pr@1.0.1
