name: Linting

on: [pull_request]

jobs:
  styles:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v1
      - name: GitHub Action for pylint
        uses: cclauss/GitHub-Action-for-pylint@master
        with:
          args: pylint --help
        id: run-linting
      - uses: github-actions-up-and-running/pr-comment@v1.0.0
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          message: Test
